# Site settings
title: Joseph Chen's blog
description: Welcome to my blog

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""
url: "http://chensunmac.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Joseph Chen
user_description: Keep curious on knowledge
user_title: System Engineer in R&D
email: chensunmac@gmail.com
twitter_username: 
github_username: chensunmac
gplus_username: chensunmac
disqus_username: chensunmac


# Name of your site (displayed in the header)
name: Joseph Chen


# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:
    id: UA-103586236-1
    host: auto  

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
